modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/unilock/YepTwo/issues"
license = "MIT"

[[mods]]
modId = "yeptwo"
version = "${version}"
displayName = "Yep"
authors = "unilock"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
logoFile = "icon.png"
displayTest = "IGNORE_SERVER_VERSION"

[[dependencies.yeptwo]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yeptwo]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
