modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/unilock/YepTwo/issues"

[[mods]]
modId = "yeptwo"
version = "${version}"
displayName = "Yep"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
logoFile = "icon.png"
authors = "unilock"

[[mixins]]
config="yeptwo.mixins.json"

[[mixins]]
config="yeptwo-neoforge.mixins.json"

[[dependencies.yeptwo]]
modId = "neoforge"
type = "required"
versionRange = "[21.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yeptwo]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"
